#!/bin/bash
# Installation of JAVA
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u73-b02/jdk-8u73-linux-x64.rpm"
sudo yum -y localinstall jdk-8u73-linux-x64.rpm
rm ~/jdk-8u*-linux-x64.rpm

# Installation of Elastic Search
sudo rpm --import http://packages.elastic.co/GPG-KEY-elasticsearch
echo '[elasticsearch-2.x]
name=Elasticsearch repository for 2.x packages
baseurl=http://packages.elastic.co/elasticsearch/2.x/centos
gpgcheck=1
gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1
' | sudo tee /etc/yum.repos.d/elasticsearch.repo
echo " network.host: localhost" >> /etc/elasticsearch/elasticsearch.yml
sudo yum -y install elasticsearch
sudo systemctl start elasticsearch
sudo systemctl enable elasticsearch

# Installation of Kibana
echo '[kibana-4.4]
name=Kibana repository for 4.4.x packages
baseurl=http://packages.elastic.co/kibana/4.4/centos
gpgcheck=1
gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1
' | sudo tee /etc/yum.repos.d/kibana.repo
sudo yum -y install kibana
echo " server.host: \"localhost\"" >> /opt/kibana/config/kibana.yml
sudo systemctl start kibana
sudo chkconfig kibana on

# Installation of Nginx
sudo yum -y install epel-release
sudo yum -y install nginx httpd-tools
#sudo htpasswd -c /etc/nginx/htpasswd.users kibanaadmin

# Installation of Logstash
echo '[logstash-2.2]
name=logstash repository for 2.2 packages
baseurl=http://packages.elasticsearch.org/logstash/2.2/centos
gpgcheck=1
gpgkey=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
enabled=1
'| sudo tee /etc/yum.repos.d/logstash.repo
sudo yum -y install logstash

# Creating certs
openssl req -config /etc/pki/tls/openssl.cnf  -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt

# Configureing Logstash
echo 'input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  }
}
'| sudo tee /etc/logstash/conf.d/02-beats-input.conf


echo 'filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    syslog_pri { }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}
' | tee /etc/logstash/conf.d/10-syslog-filter.conf 
#Test your Logstash configuration with this command:

sudo service logstash configtest
sudo systemctl restart logstash
sudo chkconfig logstash on

# Load Kibana Dashboard
cd ~
curl -L -O https://download.elastic.co/beats/dashboards/beats-dashboards-1.1.0.zip

sudo yum install -y unzip

unzip beats-dashboards-1.1.0.zip

#Load filebeat Index template in  elastic search
